import { 
  type User,
  type StencilJob, 
  type InsertStencilJob,
  type StencilStyle,
  type InsertStencilStyle,
  type FluxProject, 
  type GeminiChat, 
  type InsertFluxProject, 
  type InsertGeminiChat,
  type UsageTracking,
  type InsertUsageTracking,
  type GalleryItem,
  type InsertGalleryItem,
  users,
  userGallery,
  stencilJobs,
  stencilStyles,
  fluxProjects,
  geminiChats,
  usageTracking
} from "@shared/schema";
import { randomUUID, randomBytes } from "crypto";
import { db } from "./db";
import { eq, desc, and, sql, or } from "drizzle-orm";

// Interface for stencil processing
export interface StencilProcessRequest {
  userId: string;
  imageUrl: string;
  style: string;
  options?: {
    quality?: number;
    transparentBg?: boolean;
  };
}

// Storage interface
export interface IStorage {
  // User methods  
  getUserByEmail(email: string): Promise<User | undefined>;
  getUserByStripeCustomerId(stripeCustomerId: string): Promise<User | undefined>;
  getUserByStripeSubscriptionId(stripeSubscriptionId: string): Promise<User | undefined>;
  createUser(user: Partial<User>): Promise<User>;
  updateUser(id: string, updates: Partial<User>): Promise<User | undefined>;
  
  // Replit Auth required methods
  getUser(id: string): Promise<User | undefined>;
  upsertUser(user: Partial<User>): Promise<User>;
  
  // Credit system methods
  getUserCredits(userId: string): Promise<number>;
  deductCredits(userId: string, amount: number): Promise<boolean>;
  updateUserCredits(userId: string, newCredits: number): Promise<User>;
  addCredits(userId: string, amount: number): Promise<User>;
  
  // Stencil methods
  getStencilStyles(): Promise<StencilStyle[]>;
  getStencilStyle(id: string): Promise<StencilStyle | undefined>;
  createStencilJob(job: InsertStencilJob): Promise<StencilJob>;
  updateStencilJob(id: string, updates: Partial<StencilJob>): Promise<StencilJob | undefined>;
  getStencilJob(id: string): Promise<StencilJob | undefined>;
  getStencilJobs(userId?: string): Promise<StencilJob[]>;
  getGalleryStencils(userId?: string, limit?: number): Promise<StencilJob[]>;
  
  // Flux Kontext methods
  getFluxProjects(userId?: string): Promise<FluxProject[]>;
  createFluxProject(project: InsertFluxProject): Promise<FluxProject>;
  getFluxProject(id: string): Promise<FluxProject | undefined>;
  updateFluxProject(id: string, updates: Partial<FluxProject>): Promise<FluxProject | undefined>;
  regenerateFluxProject(id: string): Promise<FluxProject | undefined>;
  deleteFluxProject(id: string): Promise<boolean>;
  
  // Gemini chat methods
  saveGeminiChat(chat: InsertGeminiChat): Promise<GeminiChat>;
  getGeminiChats(projectId?: string): Promise<GeminiChat[]>;
  
  // Usage tracking methods
  trackUsage(usage: InsertUsageTracking): Promise<UsageTracking>;
  getUserUsage(userId: string): Promise<UsageTracking[]>;
  
  // Gallery methods
  getUserGallery(userId: string, type?: string, limit?: number, offset?: number): Promise<GalleryItem[]>;
  getGalleryItemCount(userId: string, type?: string): Promise<number>;
  getGalleryItemById(id: string): Promise<GalleryItem | undefined>;
  getGalleryItemByUrl(url: string): Promise<GalleryItem | undefined>;
  addToGallery(item: InsertGalleryItem): Promise<GalleryItem>;
  updateGalleryItem(id: string, updates: Partial<GalleryItem>, userId: string): Promise<GalleryItem | undefined>;
  deleteGalleryItem(id: string, userId: string): Promise<boolean>;
  toggleFavorite(id: string, userId: string): Promise<boolean>;
}

export class DatabaseStorage implements IStorage {
  // User methods
  async getUserByEmail(email: string): Promise<User | undefined> {
    const [user] = await db.select().from(users).where(eq(users.email, email));
    return user;
  }

  async getUserByStripeCustomerId(stripeCustomerId: string): Promise<User | undefined> {
    const [user] = await db.select().from(users).where(eq(users.stripeCustomerId, stripeCustomerId));
    return user;
  }

  async getUserByStripeSubscriptionId(stripeSubscriptionId: string): Promise<User | undefined> {
    const [user] = await db.select().from(users).where(eq(users.stripeSubscriptionId, stripeSubscriptionId));
    return user;
  }

  async createUser(user: Partial<User>): Promise<User> {
    // storageFolder will be auto-generated by PostgreSQL using gen_random_uuid()
    const [newUser] = await db.insert(users).values(user).returning();
    return newUser;
  }

  async updateUser(id: string, updates: Partial<User>): Promise<User | undefined> {
    const [updated] = await db.update(users)
      .set({ ...updates, updatedAt: new Date() })
      .where(eq(users.id, id))
      .returning();
    return updated;
  }

  // Replit Auth methods
  async getUser(id: string): Promise<User | undefined> {
    const [user] = await db.select().from(users).where(eq(users.id, id));
    return user;
  }

  async upsertUser(user: Partial<User>): Promise<User> {
    if (!user.id) {
      throw new Error("User ID is required for upsert operation");
    }
    
    const existingUser = await this.getUser(user.id);
    
    if (existingUser) {
      const [updated] = await db.update(users)
        .set({ ...user, updatedAt: new Date() })
        .where(eq(users.id, user.id))
        .returning();
      return updated;
    } else {
      // storageFolder will be auto-generated by PostgreSQL
      const [newUser] = await db.insert(users).values({
        id: user.id,
        email: user.email,
        firstName: user.firstName,
        lastName: user.lastName,
        profileImageUrl: user.profileImageUrl,
        createdAt: new Date(),
        updatedAt: new Date(),
      }).returning();
      return newUser;
    }
  }

  // Credit system methods
  async getUserCredits(userId: string): Promise<number> {
    const [user] = await db.select().from(users).where(eq(users.id, userId));
    return user?.credits || 0;
  }

  async deductCredits(userId: string, amount: number): Promise<boolean> {
    // ATOMIC TRANSACTION: Prevents race conditions and double-spending
    const result = await db.update(users)
      .set({ 
        credits: sql`GREATEST(${users.credits} - ${amount}, 0)`,
        creditsUsed: sql`${users.creditsUsed} + ${amount}`,
        updatedAt: new Date() 
      })
      .where(and(
        eq(users.id, userId),
        sql`${users.credits} >= ${amount}` // Only update if sufficient credits
      ))
      .returning({ credits: users.credits });
    
    // Return true if update succeeded (row was affected)
    return result.length > 0;
  }

  // Update available credits (not monthly allowance)
  async updateUserCredits(userId: string, newCredits: number): Promise<User> {
    const [updated] = await db.update(users)
      .set({ credits: newCredits, updatedAt: new Date() })
      .where(eq(users.id, userId))
      .returning();
    
    return updated;
  }

  // Add credits to current available balance 
  async addCredits(userId: string, amount: number): Promise<User> {
    const user = await this.getUser(userId);
    if (!user) {
      throw new Error("User not found");
    }
    
    const newTotal = (user.credits || 0) + amount;
    return this.updateUserCredits(userId, newTotal);
  }

  // Stencil methods
  async getStencilStyles(): Promise<StencilStyle[]> {
    return db.select().from(stencilStyles).orderBy(stencilStyles.displayOrder);
  }

  async getStencilStyle(id: string): Promise<StencilStyle | undefined> {
    const [style] = await db.select().from(stencilStyles).where(eq(stencilStyles.id, id));
    return style;
  }

  async createStencilJob(job: InsertStencilJob): Promise<StencilJob> {
    const [newJob] = await db.insert(stencilJobs).values(job).returning();
    return newJob;
  }

  async updateStencilJob(id: string, updates: Partial<StencilJob>): Promise<StencilJob | undefined> {
    const [updated] = await db.update(stencilJobs)
      .set(updates)
      .where(eq(stencilJobs.id, id))
      .returning();
    
    return updated;
  }

  async getStencilJob(id: string): Promise<StencilJob | undefined> {
    const [job] = await db.select().from(stencilJobs).where(eq(stencilJobs.id, id));
    return job;
  }

  async getStencilJobs(userId?: string): Promise<StencilJob[]> {
    if (userId) {
      return db.select().from(stencilJobs)
        .where(eq(stencilJobs.userId, userId))
        .orderBy(desc(stencilJobs.createdAt));
    }
    return db.select().from(stencilJobs).orderBy(desc(stencilJobs.createdAt));
  }

  async getGalleryStencils(userId?: string, limit?: number): Promise<StencilJob[]> {
    const defaultLimit = limit || 30;
    
    let baseQuery = userId 
      ? db.select().from(stencilJobs)
          .where(and(
            eq(stencilJobs.userId, userId),
            eq(stencilJobs.status, 'completed')
          ))
      : db.select().from(stencilJobs)
          .where(eq(stencilJobs.status, 'completed'));
    
    const result = await baseQuery
      .orderBy(desc(stencilJobs.createdAt))
      .limit(defaultLimit);
    
    return result;
  }

  // Flux Kontext methods
  async getFluxProjects(userId?: string): Promise<FluxProject[]> {
    console.log(`[STORAGE] getFluxProjects called for userId: ${userId}`);
    const startTime = Date.now();
    
    let result;
    if (userId) {
      result = await db.select().from(fluxProjects)
        .where(eq(fluxProjects.userId, userId))
        .orderBy(desc(fluxProjects.createdAt))
        .limit(50); // Limitar para evitar lentitud
    } else {
      result = await db.select().from(fluxProjects)
        .orderBy(desc(fluxProjects.createdAt))
        .limit(50);
    }
    
    const endTime = Date.now();
    console.log(`[STORAGE] DB query completed in ${endTime - startTime}ms, returning ${result.length} items`);
    return result;
  }

  async createFluxProject(project: InsertFluxProject): Promise<FluxProject> {
    const [newProject] = await db.insert(fluxProjects).values(project).returning();
    return newProject;
  }

  async getFluxProject(id: string): Promise<FluxProject | undefined> {
    const [project] = await db.select().from(fluxProjects)
      .where(eq(fluxProjects.id, id))
      .limit(1);
    return project;
  }

  async updateFluxProject(id: string, updates: Partial<FluxProject>): Promise<FluxProject | undefined> {
    const [updated] = await db.update(fluxProjects)
      .set({ ...updates, updatedAt: new Date() })
      .where(eq(fluxProjects.id, id))
      .returning();
    return updated;
  }

  async regenerateFluxProject(id: string): Promise<FluxProject | undefined> {
    return this.updateFluxProject(id, { updatedAt: new Date() });
  }

  async deleteFluxProject(id: string): Promise<boolean> {
    await db.delete(fluxProjects).where(eq(fluxProjects.id, id));
    return true;
  }

  // Gemini chat methods
  async saveGeminiChat(chat: InsertGeminiChat): Promise<GeminiChat> {
    const [newChat] = await db.insert(geminiChats).values(chat).returning();
    return newChat;
  }

  async getGeminiChats(projectId?: string): Promise<GeminiChat[]> {
    if (projectId) {
      return db.select().from(geminiChats)
        .where(eq(geminiChats.projectId, projectId))
        .orderBy(desc(geminiChats.createdAt));
    }
    return db.select().from(geminiChats).orderBy(desc(geminiChats.createdAt));
  }

  // Usage tracking methods
  async trackUsage(usage: InsertUsageTracking): Promise<UsageTracking> {
    const [tracked] = await db.insert(usageTracking).values(usage).returning();
    return tracked;
  }

  async getUserUsage(userId: string): Promise<UsageTracking[]> {
    return db.select().from(usageTracking)
      .where(eq(usageTracking.userId, userId))
      .orderBy(desc(usageTracking.createdAt));
  }

  // Gallery methods - SIMPLIFICADOS PARA MEJOR PERFORMANCE
  async getUserGallery(userId: string, type?: string, limit?: number, offset?: number): Promise<GalleryItem[]> {
    const defaultLimit = limit || 100;
    const defaultOffset = offset || 0;
    
    console.log(`[DB] Fetching gallery data for user ${userId}, type: ${type || 'all'}, limit: ${defaultLimit}`);
    
    const startTime = Date.now();
    
    let baseQuery = db.select().from(userGallery);
    
    if (type && type !== 'all') {
      baseQuery = baseQuery.where(and(
        eq(userGallery.userId, userId),
        eq(userGallery.type, type)
      ));
    } else {
      baseQuery = baseQuery.where(eq(userGallery.userId, userId));
    }
    
    const result = await baseQuery
      .orderBy(desc(userGallery.createdAt))
      .limit(defaultLimit)
      .offset(defaultOffset);
    
    const duration = Date.now() - startTime;
    console.log(`Gallery query took ${duration}ms for ${result.length} items`);
    
    return result;
  }

  async getGalleryItemCount(userId: string, type?: string): Promise<number> {
    let baseQuery = db.select({ count: sql<number>`count(*)` }).from(userGallery);

    if (type && type !== 'all') {
      baseQuery = baseQuery.where(and(
        eq(userGallery.userId, userId),
        eq(userGallery.type, type)
      ));
    } else {
      baseQuery = baseQuery.where(eq(userGallery.userId, userId));
    }

    const [result] = await baseQuery;
    return Number(result.count);
  }

  async getGalleryItemById(id: string): Promise<GalleryItem | undefined> {
    const [item] = await db.select().from(userGallery)
      .where(eq(userGallery.id, id));
    return item;
  }

  async getGalleryItemByUrl(url: string): Promise<GalleryItem | undefined> {
    const [item] = await db.select().from(userGallery)
      .where(or(
        eq(userGallery.imageUrl, url),
        eq(userGallery.thumbnailUrl, url)
      ));
    return item;
  }

  async addToGallery(item: InsertGalleryItem): Promise<GalleryItem> {
    const [newItem] = await db.insert(userGallery).values(item).returning();
    return newItem;
  }

  async updateGalleryItem(id: string, updates: Partial<GalleryItem>, userId: string): Promise<GalleryItem | undefined> {
    const [existing] = await db.select().from(userGallery)
      .where(and(
        eq(userGallery.id, id),
        eq(userGallery.userId, userId)
      ));

    if (!existing) {
      console.warn(`[SECURITY] User ${userId} attempted to update gallery item ${id} they don't own`);
      return undefined;
    }

    const [updated] = await db.update(userGallery)
      .set({ ...updates, updatedAt: new Date() })
      .where(and(
        eq(userGallery.id, id),
        eq(userGallery.userId, userId)
      ))
      .returning();

    return updated;
  }

  async deleteGalleryItem(id: string, userId: string): Promise<boolean> {
    await db.delete(userGallery)
      .where(and(
        eq(userGallery.id, id),
        eq(userGallery.userId, userId)
      ));
    
    return true;
  }

  async toggleFavorite(id: string, userId: string): Promise<boolean> {
    const [item] = await db.select().from(userGallery)
      .where(and(
        eq(userGallery.id, id),
        eq(userGallery.userId, userId)
      ));
    
    if (!item) return false;

    await db.update(userGallery)
      .set({ isFavorite: !item.isFavorite, updatedAt: new Date() })
      .where(eq(userGallery.id, id));
    
    return true;
  }
}

export const storage = new DatabaseStorage();